name: Managing Secrets

on:
  workflow_dispatch:
  push:

jobs:
  print_repo_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Read Repository Masked Secret
        run: echo ${{ secrets.DEV_API_KEY }}

      - name: Read Repository Secret Content
        run: echo ${{ secrets.DEV_API_KEY }} | sed 's/./& /g' # unmask secret for demo purposes

      - name: Read PRODUCTION Secret Content
        run: echo ${{ secrets.PROD_API_KEY }} | sed 's/./& /g'

  print_environment_secrets:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Read Repository Secret Content
        run: echo ${{ secrets.dev_api_key }} | sed 's/./& /g'

      - name: Read PRODUCTION Secret Content
        run: echo ${{ secrets.prod_api_key }} | sed 's/./& /g'